keys:
  - &avass age19k67f8muz2n368y2n0k55wr8z0d6q9vhh22v5re5c692v3x3af9qwsnu6a
  - &github-actions age1ra3d5axy6zhqvt5hlqpr0u8lcmf4dkapvh2uwvylqas6xc25zf5qlrnt7c
  - &windrunner age1l3y3v6trsaqep5cx5lw8jcfv5s2t7kn7q9rppfwy0vs8tmfwsu9s59pm2y
  - &reverse-proxy age1evknxp28pfhzr503rxfq3lej3pzew6mtn25vaqmadrd2edy0qdps47rjfq
creation_rules:
  - path_regex: ^nixos/hosts/reverse-proxy/.*
    key_groups:
    - age:
        - *avass
        - *github-actions
        - *reverse-proxy
  - path_regex: ^nixos/hosts/windrunner/.*
    key_groups:
    - age:
        - *avass
        - *github-actions
        - *windrunner
  - key_groups:
    - age:
        - *avass
        - *github-actions
