- hosts: all
  pre_tasks:
    - name: Import vm specific tasks
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - "{{ playbook_dir }}/files/{{ inventory_hostname }}/tasks.yaml"
          skip: true
  roles:
    - role: davfs2
      when: davfs2_enabled|default(false)
    - nixos
