- hosts: host
  roles:
    - host
  tasks:
    - name: Ensure .kube dir
      file:
        state: directory
        path: ~/.kube

    - name: Ensure cluster config
      become: true
      copy:
        remote_src: true
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_user }}"

    - name: Sync kustomization
      notify:
        - Apply kustomization
      synchronize:
        src: "{{ playbook_dir }}/k8s"
        dest: ~/
        delete: true
  handlers:
    - name: Apply kustomization
      command: kubectl apply -k ~/k8s
