- hosts: host
  roles:
    - role: host
      tags:
        - host
    - role: kubeconfig
      tags:
        - host
    - role: kubernetes-external-secrets
      tags:
        - host
    - role: kubernetes-stakater-reloader
      tags:
        - host
    - role: kustomize
      tags:
        - kustomize
