- name: Ensure /etc/davfs2/
  become: true
  file:
    path: /etc/davfs2
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Add /etc/davfs2/secrets
  become: true
  vars:
    davfs2_username: "{{ lookup('community.general.bitwarden', davfs2_secret_id, search='id', field='username') | first }}"
    davfs2_password: "{{ lookup('community.general.bitwarden', davfs2_secret_id, search='id', field='password') | first }}"
  copy:
    content: >-
      https://{{ davfs2_username }}.your-storagebox.de
      {{ davfs2_username }}
      {{ davfs2_password }}
    dest: /etc/davfs2/secrets
    mode: 0600
    owner: root
    group: root
