Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.network "public_network", dev: "bridge0", ip: "192.168.1.197"

  config.vm.provider "kvm" do |v|
    v.memory = 8096
    v.cpus = 2
  end
end
