apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-key
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  data:
    - secretKey: access-key
      remoteRef:
        key: minio/root-key
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: minio/root-key
        property: secret-key
