apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://nixos"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: kubernetes
          serviceAccountRef:
            name: external-secrets-kubernetes-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-kubernetes-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-kubernetes-auth
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: external-secrets-kubernetes-auth
  namespace: default
