apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://nixos"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-secret-store"
          key: "token"
---
# Bootstrap
apiVersion: vassast.org/v1
kind: VaultSecret
metadata:
  name: vault-secret-store
spec:
  path: kv/vault-secret-store
