#!/bin/env bash
# vim: set ft=bash:

GIT_ROOT="$(git rev-parse --show-toplevel)"

set -o allexport
eval "$(sops --output-type dotenv --extract '["env"]' -d "$GIT_ROOT/secrets.yaml")"
set +o allexport

pulumi up --cwd "$GIT_ROOT/pulumi" --stack albinvass/infra/infra "$@"
