- name: Build kubernetes objects
  environment:
    VAULT_TOKEN: "{{ lookup('env', 'VAULT_TOKEN') }}"
    VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
  register: kustomize_build
  no_log: true  # This outputs secrets
  ignore_errors: true
  command: kubectl kustomize ~/k8s --enable-alpha-plugins

- name: Show kustomization error
  when: kustomize_build.stderr
  fail:
    msg: "{{ kustomize_build.stderr }}"

- name: Apply kustomization
  register: kustomize_apply
  ignore_errors: true
  args:
    stdin: "{{ kustomize_build.stdout }}"
  command: >-
    kubectl apply -f -
    --namespace default
    --prune
    --all
    --prune-allowlist 'core/v1/ConfigMap'
    --prune-allowlist 'core/v1/Endpoints'
    --prune-allowlist 'core/v1/PersistentVolumeClaim'
    --prune-allowlist 'core/v1/Pod'
    --prune-allowlist 'core/v1/Secret'
    --prune-allowlist 'core/v1/ReplicationController'
    --prune-allowlist 'core/v1/Service'
    --prune-allowlist 'batch/v1/Job'
    --prune-allowlist 'batch/v1/CronJob'
    --prune-allowlist 'apps/v1/DaemonSet'
    --prune-allowlist 'apps/v1/Deployment'
    --prune-allowlist 'networking.k8s.io/v1/Ingress'
    --prune-allowlist 'apps/v1/ReplicaSet'
    --prune-allowlist 'apps/v1/StatefulSet'
    --prune-allowlist 'external-secrets.io/v1beta1/SecretStore'
    --prune-allowlist 'external-secrets.io/v1beta1/ClusterSecretStore'
    --prune-allowlist 'external-secrets.io/v1beta1/ExternalSecret'
    --prune-allowlist 'external-secrets.io/v1beta1/ClusterExternalSecret'

- name: Show kustomization error
  when: kustomize_apply.stderr
  fail:
    msg: "{{ kustomize_apply.stderr }}"

