Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "5.0.0"
  config.vm.network :public_network,
    :dev => "bridge0",
    :mode => "bridge",
    :type => "bridge"
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.provider "libvirt" do |v|
    v.cpus = 1
    v.memory = 1024
  end
  config.vm.provision "shell" do |s|
    ssh_pub_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjRbUx1aUZALLoWZ5L0F01QVtoPsnj7gYs9WWBBsJMbNvRZyXuYxJBCgG8YpY1W8aKaRLIsQSMMvfg62/W5ZjjnssONCUy9O56eFrxs7kNzMaobpd19WPuupfo0793c91ZM+3BnlIkZRuPZT3fCb1FFTybMJ6VThH1J3y6m2bGTcDMOWTMIxjGtc0RT61SF4luAQ81azwzyvhkP0QJnriDspy622RVcOh30lzUPYFylQwWm9lXIyBtJEwyUqc/rE4P6u230SZFkMF6GjREKIYATvdowiWMbQsONKO7emg0Wxa7ylEpduDBHIaI4ylZGc/UY8cl763rMOJ01Kjr/Zm9hjy3KskWLuOd8isYK9Pk0bmymbQ2O/edlneXPesr46x4Hm9ewD62gfINEiYHjlfEstabc1VGXEgwSKIB6YO11uFkpnICMb5RNInUZHUx1HNiTCq4+Vc5WQMKg0qGRTQmgQooO+Omu6P5MeuJHOFQdsELeTUBb+01xprsnY8vcXc= vass@albin-xps159520"
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
