- name: Ensure ~/vms
  file:
    path: ~/vms
    state: directory

- name: Copy Vagrantfile
  notify:
    - Reload
  synchronize:
    src: Vagrantfile
    dest: ~/vms

- name: Get status
  register: status
  command: vagrant status --machine-readable
  changed_when: false
  args:
    chdir: ~/vms

- name: Create vm
  when:
    - '"state,not_created" in status.stdout
      or "state,shutoff" in status.stdout'
  command: vagrant up
  args:
    chdir: ~/vms

- name: Flush handlers
  meta: flush_handlers
