- name: Ensure ~/vms
  file:
    path: ~/vms
    state: directory

- name: Copy Vagrantfile
  register: vagrantfile
  synchronize:
    src: Vagrantfile
    dest: ~/vms

- name: Get status
  register: status
  command: vagrant status --machine-readable
  changed_when: false
  args:
    chdir: ~/vms

- name: Create vm
  register: vm_create
  when:
    - '"state,not_created" in status.stdout
      or "state,shutoff" in status.stdout'
  command: vagrant up --provider=libvirt
  args:
    chdir: ~/vms

- name: Reload
  when:
    - vm_create is skipped
    - vagrantfile is changed
  command: vagrant reload
  args:
    chdir: ~/vms
