---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zuul-registry
spec:
  rules:
  - host: nixos-k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zuul-registry
            port:
              number: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-registry
  labels:
    app: zuul-registry
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: zuul-registry
...
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zuul-registry
spec:
  selector:
    matchLabels:
      app: zuul-registry
  serviceName: zuul-registry
  template:
    metadata:
      labels:
        app: zuul-registry
    spec:
      containers:
      - name: zuul-registry
        image: nixos-k3s:9000/zuul/zuul-registry:nixos-k3s-1
        args:
        - /usr/local/bin/zuul-registry
        - -d
        - -c
        - /conf/registry.yaml
        - serve
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
        - name: registry-yaml
          mountPath: /conf/
      volumes:
      - name: registry-yaml
        secret:
          secretName: registry-yaml
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
...
