apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vassast-org-homeserver-yaml
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  data:
    - secretKey: vassast-org-homeserver-yaml
      remoteRef:
        key: matrix/vassast-org-homeserver-yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vassast-org-log-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  data:
    - secretKey: vassast-org-log-config
      remoteRef:
        key: matrix/vassast-org-log-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vassast-org-signing-key
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  data:
    - secretKey: vassast-org-signing-key
      remoteRef:
        key: matrix/vassast-org-signing-key
