apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: plexinc/pms-docker #lscr.io/linuxserver/plex:1.24.4
        volumeMounts:
        - name: config
          mountPath: /config
        - name: movies
          mountPath: /movies
        - name: series
          mountPath: /series
        env:
          - name: TZ
            value: Europe/Stockholm
          - name: HOSTNAME
            value: "nixos"
          - name: PLEX_UID
            value: "10001"
          - name: PLEX_GID
            value: "10001"
          - name: PLEX_CLAIM
            valueFrom:
              secretKeyRef:
                name: plex-claim-token
                key: token
          - name: ALLOWED_NETWORKS
            value: "192.168.1.0/24"
      securityContext:
        fsGroup: 10001
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: movies
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: series
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
