Vagrant.configure("2") do |config|
  config.vm.hostname = "nixos-guest-1"
  config.vm.box = "generic/ubuntu2004"

  config.vm.network "public_network", dev: "bridge0", ip: "192.168.1.197"

  config.vm.provider "kvm" do |v|
    v.memory = 8096
    v.cpus = 2
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/authorized_keys").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
