Vagrant.configure("2") do |config|
  config.vm.define "guest-1" do |guest|
    guest.vm.hostname = "nixos-guest-1"
    guest.vm.box = "generic/ubuntu2004"

    guest.vm.network "public_network", dev: "bridge0"

    guest.vm.provider "kvm" do |v|
      v.memory = 8096
      v.cpus = 2
    end

    guest.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/authorized_keys").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
