name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v23
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: nix develop --command -- pulumi up --cwd pulumi --yes
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      - run: nix develop --command -- colmena apply
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
