name: Deploy
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Lint nix
      run: devenv shell statix check

  pulumi:
    needs: [ lint ]
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Cache Pulumi venv
      uses: actions/cache@v3
      with:
        path: pulumi/venv
        key: pulumi-venv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Provision infrastructure with pulumi
      run: devenv shell deploy-pulumi -- --yes --non-interactive
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

  colmena:
    needs: [ pulumi ]
    strategy:
      matrix:
        host:
          - nixpi
          - nixos-1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Deploy ${{ matrix.host }}
      run: devenv shell deploy-colmena -- apply --build-on-target --on ${{ matrix.host }}
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
