name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      nodes: ${{ steps.nodes.outputs.nodes }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Lint nix
      run: devenv shell statix check

    - name: Lint go
      run: devenv shell bash -- -c "cd pulumi && golangci-lint run"

    - name: Output nodes
      id: nodes
      run: echo "nodes=$(devenv shell get-enabled-nodes)" >> "$GITHUB_OUTPUT"

  pulumi:
    needs: [ pre ]
    concurrency: pulumi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Delete /usr/local/bin/pulumi-language-go
      run: sudo rm -f /usr/local/bin/pulumi-language-go

    - name: Provision infrastructure with pulumi
      run: devenv shell deploy-pulumi -- --yes --non-interactive
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

  colmena:
    needs: [ pre ]
    concurrency: colmena-${{ matrix.host }}
    strategy:
      matrix:
        host: ${{ fromJson(needs.pre.outputs.nodes) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Deploy ${{ matrix.host }}
      run: devenv shell deploy-colmena -- apply --build-on-target --on ${{ matrix.host }}
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
