name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            substituters = https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            keep-outputs = true

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v4.0.2
        with:
          key: nix-cache
          gc-linux: true
          gc-max-store-size-linux: 10000000000
          purge: true
          purge-accessed: true
          purge-accessed-max-age: 3600

      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Start ssh agent
        run: >-
          echo "SSH_AGENT_PID=$(nix develop --command -- start-ssh-agent)"
          >> $GITHUB_OUTPUT
        id: start_ssh_agent
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}

      - name: Provision Infrastructure
        run: |
          nix develop --command -- \
          pulumi up --yes --non-interactive \
            --cwd pulumi \
            --stack infra
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}

      - name: Provision Servers
        run: nix develop --command -- colmena apply
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}

      - name: Kill ssh agent
        run: >-
          nix develop --command -- kill-ssh-agent
        env:
          SSH_AGENT_PID: ${{ steps.start_ssh_agent.outputs.SSH_AGENT_PID }}
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
