providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./octodns
    default_ttl: 300
    enforce_order: false
  hetzner:
    class: octodns_hetzner.HetznerProvider
    token: env/HETZNER_DNS_TOKEN

processors:
  acme:
    class: octodns.processor.acme.AcmeMangingProcessor

zones:
  '*':
    sources:
      - config
    targets:
      - hetzner
